services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalogdb:
    image: postgres
volumes:
  postgres_catalog:
  postgres_basket:    